sudo: required

language: bash

services:
  - docker

before_install:
   - docker build -t canocles/mads-todolist-2017:1.0 .

script:
   - docker run --rm canocles/mads-todolist-2017:1.0 /bin/bash -c "sbt test"